export enum LOGIN_METHOD {
  MANUAL = "MANUAL",
  NOSTR = "NOSTR",
  PRIVATE_KEY = "PRIVATE_KEY",
  EMAIL_MAGIC_LINK = "EMAIL_MAGIC_LINK",
  GOOGLE = "GOOGLE",
  GITHUB = "GITHUB",
}

export const LOGIN_METHOD_NOSTR = [
  LOGIN_METHOD.NOSTR,
  LOGIN_METHOD.PRIVATE_KEY,
  LOGIN_METHOD.MANUAL,
];
export const LOGIN_METHOD_EMAIL_MAGIC_LINK = [LOGIN_METHOD.EMAIL_MAGIC_LINK];
export const LOGIN_METHOD_GOOGLE = [LOGIN_METHOD.GOOGLE];
export const LOGIN_METHOD_GITHUB = [LOGIN_METHOD.GITHUB];
